remote_theme: pages-themes/modernist@v0.2.0
title: Rune & Emilie sin side
description: En side med nyttige ting vi vil huske


# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

theme: jekyll-theme-cayman